// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmjfsfcygvbuirujqaey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtamZzZmN5Z3ZidWlydWpxYWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTU2NjQsImV4cCI6MjA3MTI5MTY2NH0.c7y8sw5NJIpLFFH4z8vpL5MzJAFpKL1k2Zpt46T7oDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});